baseURL = "https://makejarnotwar.com/"
languageCode = "en-us"
title = "VMWare Tanzu Developer Advocates"
theme = "castanet"

# see https://github.com/mattstratton/castanet/blob/master/REFERENCE.md
[params]
mainSections = ["episode"]
site_theme = "grey"
site_layout = "grid"
# site_layout = "row"
enable_jumbo = "true"
copyright_notice = "Copyright 2020 [VMware](https://www.vmware.com), Inc &bullet; [Terms of Use](https://www.vmware.com/help/legal.html) &bullet; [Privacy Policy](https://www.vmware.com/help/privacy.html)"
description = "Tanzu Tuesdays streams Live on Twitch every Tuesday at 1 PM PT."

  [params.social]
  github = "vmware-tanzu/tanzu-tuesdays"
  youtube = "channel/UC2YjasM1YNeYEmDOhw9R5mg"
  twitch = "makejarnotwar"

  [params.authors]
    [params.authors.paulczar]
      name	= "Paul Czarkowski"
      bio   = "Paul is great"
      thumbnail = "img/hosts/paulczar.jpg"
    [params.authors.paulczar.social]
      twitter = "pczarkowski"

    [params.authors.bob]
      name	= "Robert Brindley"
      bio   = "Drinks the good whiskey."
      thumbnail = "img/hosts/bob.jpg"
    [params.authors.bob.social]
      twitter = "bob_brindley"

    [params.authors.tiffany]
      name	= "tiffany jernigan"
      bio   = "<insert bio here :3>"
      thumbnail = "img/hosts/tiffany.jpg"
    [params.authors.tiffany.social]
      twitter = "tiffanyfayj"

  [params.links]
    [params.links.vmware]
      name = "VMware"
      url = "https://vmware.com"

#[[Menu.Main]]
#    name = "About"
#    identifier = "about"
#    url = "about"

#[[Menu.Main]]
#    name = "Contact"
#    identifier = "contact"
#    url = "contact"

[[Menu.Main]]
    name = "Hosts"
    identifier = "02-hosts"
    url = "/host"

[[Menu.Main]]
    name = "Episodes"
    identifier = "01-episodes"
    url = "/"

[[Menu.Main]]
    name = "Guests"
    identifier = "03-guest"
    url = "/guest"

[[Menu.Main]]
    name = "Advocates"
    identifier = "04-advocates"
    url = "/advocate"
